### ISSUE TITLE
GPU Resources

### ISSUE THREAD

**Issue by lovelyczli** [zhiheLu/Ensemble_VLM#1]
Thanks for your work!
Could you pls provide specific details regarding the GPU resources, data requirements, and estimated training time
I am planning to utilize your code, and this information will be crucial for my preparations and resource allocation.

Thank you for your time and assistance. I look forward to your response.

**Comment by zhiheLu** [comment]
Thanks for your interest!

We run experiments on one V100 GPU and the training is quick, from a few minutes to a few hours depending on the size of dataset. The dataset information can be found at DATASETS.md.
